"""first migration

Revision ID: 97d6926efd71
Revises: 
Create Date: 2026-08-27 10:28:57.185737

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d6926efd71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip_postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.CheckConstraint('LENGTH(zip_postal_code) <= 20', name='check_zip_length'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='check_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='check_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_city_state', 'address', ['city', 'state'], unique=False)
    op.create_index('idx_address_country_zip', 'address', ['country', 'zip_postal_code'], unique=False)
    op.create_index(op.f('ix_address_created_at'), 'address', ['created_at'], unique=False)
    op.create_index(op.f('ix_address_is_deleted'), 'address', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_address_updated_at'), 'address', ['updated_at'], unique=False)
    op.create_table('outbox_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_message_available_at'), 'outbox_message', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_message_created_at'), 'outbox_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_message_event_type'), 'outbox_message', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_message_status'), 'outbox_message', ['status'], unique=False)
    op.create_table('user',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('audit_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_changes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['audit_action', 'created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_time', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_updated_at'), 'audit_log', ['updated_at'], unique=False)
    op.create_table('identityverification',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_status', sa.Enum('NOT_STARTED', 'DOCUMENTS_UPLOADED', 'PENDING_REVIEW', 'UNDER_REVIEW', 'ADDITIONAL_INFO_REQUIRED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'FLAGGED_FOR_FRAUD', name='verificationstatusenum'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identityverification_created_at'), 'identityverification', ['created_at'], unique=False)
    op.create_index(op.f('ix_identityverification_is_deleted'), 'identityverification', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_identityverification_updated_at'), 'identityverification', ['updated_at'], unique=False)
    op.create_index(op.f('ix_identityverification_user_id'), 'identityverification', ['user_id'], unique=True)
    op.create_table('logineventinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operating_system', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_ip', 'logineventinfo', ['ip_address'], unique=False)
    op.create_index('idx_login_success', 'logineventinfo', ['is_successful', 'occurred_at'], unique=False)
    op.create_index('idx_login_user_time', 'logineventinfo', ['user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_logineventinfo_occurred_at'), 'logineventinfo', ['occurred_at'], unique=False)
    op.create_table('organisation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sa.Enum('NGN', 'USD', 'GBP', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('TRIAL', 'PRO', 'ENTERPRISE', name='subscriptionplanenum'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'INACTIVE', 'PAST_DUE', 'CANCELLED', name='subscriptionstatusenum'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_created_at'), 'organisation', ['created_at'], unique=False)
    op.create_index(op.f('ix_organisation_email'), 'organisation', ['email'], unique=True)
    op.create_index(op.f('ix_organisation_is_deleted'), 'organisation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organisation_organisation_name'), 'organisation', ['organisation_name'], unique=True)
    op.create_index(op.f('ix_organisation_updated_at'), 'organisation', ['updated_at'], unique=False)
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_permission_module', 'permission', ['module'], unique=False)
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_created_at'), 'permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_permission_updated_at'), 'permission', ['updated_at'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sa.Enum('PLATFORM', 'ORGANISATION', name='rolescope'), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_assignable_role', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created_at'), 'role', ['created_at'], unique=False)
    op.create_index(op.f('ix_role_display_name'), 'role', ['display_name'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_index(op.f('ix_role_scope'), 'role', ['scope'], unique=False)
    op.create_index(op.f('ix_role_updated_at'), 'role', ['updated_at'], unique=False)
    op.create_table('useraddress',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('address_type', sa.Enum('HOME', 'OFFICE', 'SHIPPING', 'BILLING', name='addresstypeenum'), nullable=False),
    sa.Column('is_default_address', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    op.create_index(op.f('ix_useraddress_address_type'), 'useraddress', ['address_type'], unique=False)
    op.create_index(op.f('ix_useraddress_is_deleted'), 'useraddress', ['is_deleted'], unique=False)
    op.create_table('usersecurityprofile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('login_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersecurityprofile_created_at'), 'usersecurityprofile', ['created_at'], unique=False)
    op.create_index(op.f('ix_usersecurityprofile_last_login'), 'usersecurityprofile', ['last_login'], unique=False)
    op.create_index(op.f('ix_usersecurityprofile_updated_at'), 'usersecurityprofile', ['updated_at'], unique=False)
    op.create_index(op.f('ix_usersecurityprofile_user_id'), 'usersecurityprofile', ['user_id'], unique=True)
    op.create_table('identitydocument',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'NATIONAL_ID', 'BANK_VERIFICATION_NO', 'DRIVERS_LICENSE', 'UTILITY_BILL', 'SELFIE', 'BANK_STATEMENT', 'VOTER_CARD', 'RESIDENCE_PERMIT', 'INTERNATIONAL_PASSPORT', 'BUSINESS_REGISTRATION_DOCUMENT', name='documenttypeenum'), nullable=False),
    sa.Column('document_number_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_number_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['identityverification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identitydocument_document_number_hash'), 'identitydocument', ['document_number_hash'], unique=False)
    op.create_index(op.f('ix_identitydocument_is_deleted'), 'identitydocument', ['is_deleted'], unique=False)
    op.create_table('organisation_member',
    sa.Column('employee_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'PENDING', 'ACTIVE', 'SUSPENDED', 'LEFT', 'REMOVED', name='membershipstatus'), nullable=False),
    sa.Column('joined_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organisation_id'),
    sa.UniqueConstraint('user_id', 'organisation_id', name='uq_org_member_user_org')
    )
    op.create_index('idx_org_member_joined', 'organisation_member', ['joined_date'], unique=False)
    op.create_index('idx_org_member_status', 'organisation_member', ['organisation_id', 'status'], unique=False)
    op.create_index('idx_org_member_user_status', 'organisation_member', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_organisation_member_employee_number'), 'organisation_member', ['employee_number'], unique=True)
    op.create_table('rolepermission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('idx_role_permission', 'rolepermission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rolepermission_created_at'), 'rolepermission', ['created_at'], unique=False)
    op.create_index(op.f('ix_rolepermission_updated_at'), 'rolepermission', ['updated_at'], unique=False)
    op.create_table('roleassignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('valid_until IS NULL OR valid_until > valid_from', name='ck_role_assignment_valid_period'),
    sa.ForeignKeyConstraint(['assigned_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_assigner_role_assignment_membership'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_user_role_assignment_membership', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_assign_active_period', 'roleassignment', ['is_active', 'valid_from', 'valid_until'], unique=False)
    op.create_index('idx_role_assign_dates', 'roleassignment', ['valid_from', 'valid_until'], unique=False)
    op.create_index('idx_role_assign_user_current', 'roleassignment', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_role_assign_user_role', 'roleassignment', ['user_id', 'role_id'], unique=False)
    op.create_index('idx_role_assignment_org_role', 'roleassignment', ['organisation_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_roleassignment_is_active'), 'roleassignment', ['is_active'], unique=False)
    op.create_index(op.f('ix_roleassignment_organisation_id'), 'roleassignment', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_roleassignment_role_id'), 'roleassignment', ['role_id'], unique=False)
    op.create_index(op.f('ix_roleassignment_user_id'), 'roleassignment', ['user_id'], unique=False)
    op.create_table('store',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sa.Enum('NGN', 'USD', 'GBP', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', name='storestatusenum'), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['created_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_store_creator_membership'),
    sa.ForeignKeyConstraint(['manager_id', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_store_manager_membership'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['updated_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_store_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organisation_id', name='uq_store_id_organisation'),
    sa.UniqueConstraint('organisation_id', 'store_code', name='uq_store_organisation_code')
    )
    op.create_index('idx_store_org', 'store', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_store_created_at'), 'store', ['created_at'], unique=False)
    op.create_index(op.f('ix_store_created_by'), 'store', ['created_by'], unique=False)
    op.create_index(op.f('ix_store_email'), 'store', ['email'], unique=False)
    op.create_index(op.f('ix_store_is_deleted'), 'store', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_store_manager_id'), 'store', ['manager_id'], unique=False)
    op.create_index(op.f('ix_store_store_code'), 'store', ['store_code'], unique=False)
    op.create_index(op.f('ix_store_updated_at'), 'store', ['updated_at'], unique=False)
    op.create_table('warehouse',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_storage_units', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'CLOSED', name='warehousestatusenum'), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['created_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_warehouse_creator_membership'),
    sa.ForeignKeyConstraint(['manager_id', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_warehouse_manager_membership'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['updated_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], name='fk_warehouse_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organisation_id', name='uq_warehouse_id_organisation'),
    sa.UniqueConstraint('organisation_id', 'warehouse_code', name='uq_warehouse_organisation_code')
    )
    op.create_index('idx_warehouse_org', 'warehouse', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_warehouse_created_at'), 'warehouse', ['created_at'], unique=False)
    op.create_index(op.f('ix_warehouse_created_by'), 'warehouse', ['created_by'], unique=False)
    op.create_index(op.f('ix_warehouse_email'), 'warehouse', ['email'], unique=False)
    op.create_index(op.f('ix_warehouse_is_deleted'), 'warehouse', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_warehouse_manager_id'), 'warehouse', ['manager_id'], unique=False)
    op.create_index(op.f('ix_warehouse_updated_at'), 'warehouse', ['updated_at'], unique=False)
    op.create_index(op.f('ix_warehouse_warehouse_code'), 'warehouse', ['warehouse_code'], unique=False)
    op.create_table('storestaff',
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('removed_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='staffassignmentstatus'), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary_store', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], ),
    sa.ForeignKeyConstraint(['removed_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], ),
    sa.ForeignKeyConstraint(['staff_id', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], ),
    sa.ForeignKeyConstraint(['store_id', 'organisation_id'], ['store.id', 'store.organisation_id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'organisation_id', 'store_id')
    )
    op.create_index('idx_store_staff', 'storestaff', ['staff_id', 'organisation_id'], unique=False)
    op.create_index('idx_store_staff_store', 'storestaff', ['store_id', 'organisation_id'], unique=False)
    op.create_table('warehousestaff',
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('removed_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='staffassignmentstatus'), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], ),
    sa.ForeignKeyConstraint(['removed_by', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], ),
    sa.ForeignKeyConstraint(['staff_id', 'organisation_id'], ['organisation_member.user_id', 'organisation_member.organisation_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id', 'organisation_id'], ['warehouse.id', 'warehouse.organisation_id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'organisation_id', 'warehouse_id')
    )
    op.create_index('idx_warehouse_staff', 'warehousestaff', ['staff_id', 'organisation_id'], unique=False)
    op.create_index('idx_warehouse_staff_warehouse', 'warehousestaff', ['warehouse_id', 'organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_warehouse_staff_warehouse', table_name='warehousestaff')
    op.drop_index('idx_warehouse_staff', table_name='warehousestaff')
    op.drop_table('warehousestaff')
    op.drop_index('idx_store_staff_store', table_name='storestaff')
    op.drop_index('idx_store_staff', table_name='storestaff')
    op.drop_table('storestaff')
    op.drop_index(op.f('ix_warehouse_warehouse_code'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_updated_at'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_manager_id'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_is_deleted'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_email'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_created_by'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_created_at'), table_name='warehouse')
    op.drop_index('idx_warehouse_org', table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_store_updated_at'), table_name='store')
    op.drop_index(op.f('ix_store_store_code'), table_name='store')
    op.drop_index(op.f('ix_store_manager_id'), table_name='store')
    op.drop_index(op.f('ix_store_is_deleted'), table_name='store')
    op.drop_index(op.f('ix_store_email'), table_name='store')
    op.drop_index(op.f('ix_store_created_by'), table_name='store')
    op.drop_index(op.f('ix_store_created_at'), table_name='store')
    op.drop_index('idx_store_org', table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_roleassignment_user_id'), table_name='roleassignment')
    op.drop_index(op.f('ix_roleassignment_role_id'), table_name='roleassignment')
    op.drop_index(op.f('ix_roleassignment_organisation_id'), table_name='roleassignment')
    op.drop_index(op.f('ix_roleassignment_is_active'), table_name='roleassignment')
    op.drop_index('idx_role_assignment_org_role', table_name='roleassignment')
    op.drop_index('idx_role_assign_user_role', table_name='roleassignment')
    op.drop_index('idx_role_assign_user_current', table_name='roleassignment')
    op.drop_index('idx_role_assign_dates', table_name='roleassignment')
    op.drop_index('idx_role_assign_active_period', table_name='roleassignment')
    op.drop_table('roleassignment')
    op.drop_index(op.f('ix_rolepermission_updated_at'), table_name='rolepermission')
    op.drop_index(op.f('ix_rolepermission_created_at'), table_name='rolepermission')
    op.drop_index('idx_role_permission', table_name='rolepermission')
    op.drop_table('rolepermission')
    op.drop_index(op.f('ix_organisation_member_employee_number'), table_name='organisation_member')
    op.drop_index('idx_org_member_user_status', table_name='organisation_member')
    op.drop_index('idx_org_member_status', table_name='organisation_member')
    op.drop_index('idx_org_member_joined', table_name='organisation_member')
    op.drop_table('organisation_member')
    op.drop_index(op.f('ix_identitydocument_is_deleted'), table_name='identitydocument')
    op.drop_index(op.f('ix_identitydocument_document_number_hash'), table_name='identitydocument')
    op.drop_table('identitydocument')
    op.drop_index(op.f('ix_usersecurityprofile_user_id'), table_name='usersecurityprofile')
    op.drop_index(op.f('ix_usersecurityprofile_updated_at'), table_name='usersecurityprofile')
    op.drop_index(op.f('ix_usersecurityprofile_last_login'), table_name='usersecurityprofile')
    op.drop_index(op.f('ix_usersecurityprofile_created_at'), table_name='usersecurityprofile')
    op.drop_table('usersecurityprofile')
    op.drop_index(op.f('ix_useraddress_is_deleted'), table_name='useraddress')
    op.drop_index(op.f('ix_useraddress_address_type'), table_name='useraddress')
    op.drop_table('useraddress')
    op.drop_index(op.f('ix_role_updated_at'), table_name='role')
    op.drop_index(op.f('ix_role_scope'), table_name='role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_display_name'), table_name='role')
    op.drop_index(op.f('ix_role_created_at'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_updated_at'), table_name='permission')
    op.drop_index(op.f('ix_permission_created_at'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_index('idx_permission_module', table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_organisation_updated_at'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_organisation_name'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_is_deleted'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_email'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_created_at'), table_name='organisation')
    op.drop_table('organisation')
    op.drop_index(op.f('ix_logineventinfo_occurred_at'), table_name='logineventinfo')
    op.drop_index('idx_login_user_time', table_name='logineventinfo')
    op.drop_index('idx_login_success', table_name='logineventinfo')
    op.drop_index('idx_login_ip', table_name='logineventinfo')
    op.drop_table('logineventinfo')
    op.drop_index(op.f('ix_identityverification_user_id'), table_name='identityverification')
    op.drop_index(op.f('ix_identityverification_updated_at'), table_name='identityverification')
    op.drop_index(op.f('ix_identityverification_is_deleted'), table_name='identityverification')
    op.drop_index(op.f('ix_identityverification_created_at'), table_name='identityverification')
    op.drop_table('identityverification')
    op.drop_index(op.f('ix_audit_log_updated_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index('idx_audit_user_time', table_name='audit_log')
    op.drop_index('idx_audit_resource', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_outbox_message_status'), table_name='outbox_message')
    op.drop_index(op.f('ix_outbox_message_event_type'), table_name='outbox_message')
    op.drop_index(op.f('ix_outbox_message_created_at'), table_name='outbox_message')
    op.drop_index(op.f('ix_outbox_message_available_at'), table_name='outbox_message')
    op.drop_table('outbox_message')
    op.drop_index(op.f('ix_address_updated_at'), table_name='address')
    op.drop_index(op.f('ix_address_is_deleted'), table_name='address')
    op.drop_index(op.f('ix_address_created_at'), table_name='address')
    op.drop_index('idx_address_country_zip', table_name='address')
    op.drop_index('idx_address_city_state', table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
